server:
  error:
    include-message: never
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGUSER}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        auto: create
        ddl-auto: update
api:
  security:
    token:
      secret: ${JWT_SECRET:secret-key}