server:
  error:
    include-message: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_senna?serverTimezone=UTC
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        auto: create
        ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG