name: Run unit tests

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          java-package: 'jdk'
          distribution: 'adopt'

      - name: Run unit tests
        run: mvn test
